package com.saga.orchestrator.domain.model.enums;

public enum WorkflowState {
    ITEM_SERVICING_INITIATED,
    USER_ACTION_RETURN_TO_WAREHOUSE,
    USER_ACTION_RETURN_TO_WAREHOUSE_COMPLETED,
    SERVICE_ON_SITE,
    USER_ACTION_IS_FOR_REFUND,
    USER_ACTION_IS_FOR_REFUND_RESULT,
    REFUND_INITIATED,
    CREATE_SHIPMENT,
    ASSIGN_COURIER,
    ASSIGN_COURIER_COMPLETED,
    WAIT_FOR_DELIVERY,
    DELIVERED,
    ITEM_SERVICING_COMPLETED
}
