spring:
  application:
    name: orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5431/orchestratordb
    password: postgres
    username: postgres
  cloud:
    function:
      definition: startWorkflowProcess;claimCreated;shipmentCreated;packageDelivered;courierAssigned;warehouseNotified;notifiedOfDelivery;checkDelivery;
    config:
      enable: true
    stream:
      kafka:
        default:
          producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer:
            enableDlq: false
            autoCommitOnError: true
            autoCommitOffset: true
        binder:
          brokers: localhost:9092
          minPartitionCount: 4
          autoAddPartitions: true
          consumerProperties:
            enable.auto.commit: true
            fetch.max.bytes: 62194560
            session.timeout.ms: 15000
          producerProperties:
            retries: 3
            batch.size: 16384
            buffer.memory: 33554432
            linger.ms: 1
      bindings:
        startWorkflowProcess-in-0:
          destination: workflow-start-process
          content-type: application/json
          group: workflow-group
        claimCreated-in-0:
          destination: workflow-claim-create-response
          content-type: application/json
          group: workflow-group
        shipmentCreated-in-0:
          destination: workflow-shipment-create-response
          content-type: application/json
          group: workflow-group
        courierAssigned-in-0:
          destination: workflow-courier-assign-response
          content-type: application/json
          group: workflow-group
        packageDelivered-in-0:
          destination: workflow-courier-delivered-response
          content-type: application/json
          group: workflow-group
        warehouseNotified-in-0:
          destination: workflow-courier-notify-warehouse-response
          content-type: application/json
        checkDelivery-in-0:
          destination: workflow-shipment-check-delivery-response
          content-type: application/json
          group: workflow-group
        notifiedOfDelivery-in-0:
          destination: workflow-delivered-package-response
          content-type: application/json
          group: workflow-group
logging:
  level:
    org.apache.kafka: ERROR